In [1]:
import pandas as pd

In [7]:
property_data = pd.read_csv("/Users/hamid/Documents/GitHub/workbook_mcimolini_W2026/Module 11/Day 35/jupyter_pandas_fundamentals_start/data/Property_Assessment_Data_(Current_Calendar_Year)_20251030.csv",low_memory=False)

In [4]:
property_data.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
0,4058129,NaN,870.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,150000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
1,4058137,NaN,872.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,149500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
2,4058145,NaN,874.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,151500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
3,4058152,NaN,876.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,147000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
4,4058160,NaN,878.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,153500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)

In [5]:
property_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 431706 entries, 0 to 431705
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Account Number        431706 non-null  int64
 1   Suite                 82839 non-null   object
 2   House Number          386360 non-null  float64
 3   Street Name           386360 non-null  object
 4   Neighbourhood ID      423470 non-null  float64
 5   Neighbourhood         431706 non-null  object
 6   Ward                  423470 non-null  object
 7   Assessed Value        431706 non-null  int64
 8   Tax Class             431706 non-null  object
 9   Garage                431706 non-null  object
 10  Assessment Class 1    431706 non-null  object
 11  Assessment Class 2    1096 non-null    object
 12  Assessment Class 3    283 non-null     object
 13  Assessment Class % 1  431706 non-null  int64
 14  Assessment Class % 2  1096 non-null    float64
 15  Assessment Class % 3  283 non-null     float64
 16  Latitude              431706 non-null  float64
 17  Longitude             431706 non-null  float64
 18  Point Location        431706 non-null  object
dtypes: float64(6), int64(3), object(10)
memory usage: 62.6+ MB

In [6]:
property_data.shape

(431706, 19)

In [8]:
property_data.describe()

,Account Number,House Number,Neighbourhood ID,Assessed Value,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude
count,4.317060e+05,386360.000000,423470.000000,4.317060e+05,431706.000000,1096.000000,283.000000,431706.000000,431706.000000
mean,7.932009e+06,7715.353792,4274.007878,5.097698e+05,99.952975,17.537409,3.243816,53.517496,-113.514320
std,3.266791e+06,5494.706696,1756.729000,3.770018e+06,1.214058,15.312706,3.522056,0.068877,0.085176
min,1.001007e+06,1.000000,1010.000000,0.000000e+00,41.000000,1.000000,1.000000,53.338595,-113.713318
25%,4.763971e+06,2513.750000,2660.000000,1.800000e+05,100.000000,3.000000,1.000000,53.457364,-113.573817
50%,9.985830e+06,7916.000000,4487.000000,3.690000e+05,100.000000,13.000000,2.000000,53.519346,-113.510660
75%,1.027426e+07,11431.000000,5579.000000,5.005000e+05,100.000000,32.000000,4.000000,53.572620,-113.448507
max,1.131654e+07,51175.000000,8889.000000,1.289650e+09,100.000000,50.000000,24.000000,53.715150,-113.278411

In [9]:
property_data["Neighbourhood"].unique()

array(['ABBOTTSFIELD', 'ALBANY', 'ALBERTA AVENUE',
       'ALBERTA PARK INDUSTRIAL', 'ALCES', 'ALDERGROVE', 'ALLARD',
       'ALLENDALE', 'AMBLESIDE', 'ANTHONY HENDAY',
       'ANTHONY HENDAY BIG LAKE', 'ANTHONY HENDAY CASTLEDOWNS',
       'ANTHONY HENDAY CLAREVIEW', 'ANTHONY HENDAY ENERGY PARK',
       'ANTHONY HENDAY HORSE HILL', 'ANTHONY HENDAY LAKE DISTRICT',
       'ANTHONY HENDAY MISTATIM', 'ANTHONY HENDAY RAMPART',
       'ANTHONY HENDAY SOUTH', 'ANTHONY HENDAY SOUTH BLACKBURNE',
       'ANTHONY HENDAY SOUTH WEST', 'ANTHONY HENDAY SOUTHEAST',
       'ANTHONY HENDAY TERWILLEGAR', 'ARGYLL', 'ARMSTRONG INDUSTRIAL',
       'ASPEN GARDENS', 'ASTER', 'ATHLONE', 'AVONMORE', 'BALWIN',
       'BANNERMAN', 'BARANOW', 'BATURYN', 'BEACON HEIGHTS', 'BEARSPAW',
       'BEAUMARIS', 'BELGRAVIA', 'BELLE RIVE', 'BELLEVUE', 'BELMEAD',
       'BELMONT', 'BELVEDERE', 'BERGMAN', 'BEVERLY HEIGHTS', 'BISSET',
       'BLACKBURNE', 'BLACKMUD CREEK', 'BLACKMUD CREEK RAVINE',
       'BLATCHFORD AREA', 'BLUE QUILL', 'BLUE QUILL ESTATES',
       'BONAVENTURE INDUSTRIAL', 'BONNIE DOON', 'BOYLE STREET',
       'BRANDER GARDENS', 'BRECKENRIDGE GREENS', 'BRINTNELL',
       'BRITANNIA YOUNGSTOWN', 'BROOKSIDE', 'BROWN INDUSTRIAL',
       'BULYEA HEIGHTS', 'CAERNARVON', 'CALDER', 'CALGARY TRAIL NORTH',
       'CALGARY TRAIL SOUTH', 'CALLAGHAN', 'CALLINGWOOD NORTH',
       'CALLINGWOOD SOUTH', 'CAMERON HEIGHTS', 'CANON RIDGE', 'CANORA',
       'CANOSSA', 'CAPILANO', 'CARLETON SQUARE INDUSTRIAL', 'CARLISLE',
       'CARLTON', 'CARTER CREST', 'CASHMAN', 'CASSELMAN', 'CAVANAGH',
       'CENTRAL MCDOUGALL', 'CHAMBERY', 'CHAPPELLE', 'CHAPPELLE AREA',
       'CHARLESWORTH', 'CLAREVIEW TOWN CENTRE', 'CLOVER BAR AREA',
       'CLOVERDALE', 'CORONET ADDITION INDUSTRIAL', 'CORONET INDUSTRIAL',
       'CPR IRVINE', 'CRAWFORD PLAINS', 'CRESTWOOD', 'CROMDALE',
       'CROSSROADS', 'CRYSTALLINA NERA EAST', 'CRYSTALLINA NERA WEST',
       'CUMBERLAND', 'CY BECKER', 'DALY GROVE', 'DAVIES INDUSTRIAL EAST',
       'DAVIES INDUSTRIAL WEST', 'DECHENE', 'DECOTEAU', 'DELTON',
       'DELWOOD', 'DESROCHERS AREA', 'DOMINION INDUSTRIAL', 'DONSDALE',
       'DOVERCOURT', 'DOWNTOWN', 'DUGGAN', 'DUNLUCE',
       'EASTGATE BUSINESS PARK', 'EASTWOOD', 'EAUX CLAIRES', 'EBBERS',
       'EDGEMONT', 'EDMISTON INDUSTRIAL',
       'EDMONTON ENERGY AND TECHNOLOGY PARK', 'EDMONTON NORTHLANDS',
       'EDMONTON RESEARCH AND DEVEL PARK', 'EDMONTON SOUTH CENTRAL',
       'EDMONTON SOUTH CENTRAL EAST', 'EDMONTON SOUTH EAST',
       'EDMONTON SOUTH WEST', 'EKOTA', 'ELLERSLIE',
       'ELLERSLIE INDUSTRIAL', 'ELMWOOD', 'ELMWOOD PARK', 'ELSINORE',
       'EMPIRE PARK', 'ERMINESKIN', 'EVANSDALE', 'EVERGREEN',
       'FALCONER HEIGHTS', 'FOREST HEIGHTS', 'FRASER', 'FULTON PLACE',
       'GAGNON ESTATE INDUSTRIAL', 'GAINER INDUSTRIAL', 'GARIEPY',
       'GARNEAU', 'GARSIDE INDUSTRIAL', 'GIRARD INDUSTRIAL',
       'GLASTONBURY', 'GLENGARRY', 'GLENORA', 'GLENRIDDING HEIGHTS',
       'GLENRIDDING RAVINE', 'GLENWOOD', 'GOLD BAR', 'GOODRIDGE CORNERS',
       'GORMAN', 'GRANDVIEW HEIGHTS', 'GRANVILLE', 'GRAYDON HILL',
       'GREENFIELD', 'GREENVIEW', 'GRIESBACH', 'GROVENOR', 'HADDOW',
       'HAGMANN ESTATE INDUSTRIAL', 'HAIRSINE',
       'HAWIN PARK ESTATE INDUSTRIAL', 'HAWKS RIDGE', 'HAYS RIDGE AREA',
       'HAZELDEAN', 'HENDERSON ESTATES', 'HERITAGE VALLEY AREA',
       'HERITAGE VALLEY TOWN CENTRE AREA', 'HIGH PARK',
       'HIGH PARK INDUSTRIAL', 'HIGHLANDS', 'HILLVIEW', 'HODGSON',
       'HOLLICK-KENYON', 'HOLYROOD', 'HOMESTEADER', 'HUDSON',
       'HUFF BREMNER ESTATE INDUSTRIAL', 'IDYLWYLDE',
       'INDUSTRIAL HEIGHTS', 'INGLEWOOD', 'JACKSON HEIGHTS',
       'JAMIESON PLACE', 'JASPER PARK', 'KAMEYOSEK', 'KEHEEWIN',
       'KENILWORTH', 'KENNEDALE INDUSTRIAL', 'KENSINGTON', 'KERNOHAN',
       'KESWICK', 'KILDARE', 'KILKENNY', 'KILLARNEY', 'KING EDWARD PARK',
       'KINGLET GARDENS', 'KINISKI GARDENS', 'KINOKAMAU PLAINS AREA',
       'KIRKNESS', 'KLARVATTEN', 'LA PERLE', 'LAGO LINDO',
       'LAMBTON INDUSTRIAL', 'LANSDOWNE', 'LARKSPUR', 'LAUDERDALE',
       'LAUREL', 'LAURIER HEIGHTS', 'LEE RIDGE', 'LEGER', 'LENDRUM PLACE',
       'LEWIS FARMS INDUSTRIAL', 'LORELEI', 'LYMBURN', 'LYNNWOOD',
       'MACEWAN', 'MACTAGGART', 'MAGRATH HEIGHTS', 'MALMO PLAINS',
       'MAPLE', 'MAPLE RIDGE', 'MAPLE RIDGE INDUSTRIAL', 'MARQUIS',
       'MATT BERRY', 'MATTSON', 'MAYFIELD', 'MAYLIEWAN',
       'MCARTHUR INDUSTRIAL', 'MCCAULEY', 'MCCONACHIE',
       'MCINTYRE INDUSTRIAL', 'MCKERNAN', 'MCLEOD', 'MCNAMARA INDUSTRIAL',
       'MCQUEEN', 'MEADOWLARK PARK', 'MELTWATER', 'MENISA', 'MEYOKUMIN',
       'MEYONOHK', 'MICHAELS PARK', 'MILL CREEK RAVINE NORTH',
       'MILL CREEK RAVINE SOUTH', 'MILL WOODS PARK',
       'MILL WOODS TOWN CENTRE', 'MILLER', 'MINCHAU',
       'MISTATIM INDUSTRIAL', 'MITCHELL INDUSTRIAL', 'MONTROSE',
       'MORIN INDUSTRIAL', 'MORRIS INDUSTRIAL', 'NEWTON', 'NORTH GLENORA',
       'NORTHMOUNT', 'NORWESTER INDUSTRIAL', 'OGILVIE RIDGE', 'OLESKIW',
       'OLIVER', 'ORMSBY PLACE', 'OTTEWELL', 'OVERLANDERS', 'OXFORD',
       'OZERNA', 'PAISLEY', 'PAPASCHASE INDUSTRIAL', 'PARKALLEN',
       'PARKDALE', 'PARKVIEW', 'PARSONS INDUSTRIAL', 'PATRICIA HEIGHTS',
       'PEMBINA', 'PINTAIL LANDING', 'PLACE LA RUE', 'PLEASANTVIEW',
       'POLLARD MEADOWS', 'POTTER GREENS', 'POUNDMAKER INDUSTRIAL',
       'PRINCE CHARLES', 'PRINCE RUPERT', 'PYLYPOW INDUSTRIAL',
       'QUARRY RIDGE', 'QUEEN ALEXANDRA', 'QUEEN MARY PARK',
       'QUESNELL HEIGHTS', 'RAMPART INDUSTRIAL', 'RAMSAY HEIGHTS',
       'RAPPERSWIL', 'RHATIGAN RIDGE', 'RICHFIELD', 'RICHFORD',
       'RIDEAU PARK', 'RIO TERRACE', 'RITCHIE', 'RIVER VALLEY CAMERON',
       'RIVER VALLEY CAPITOL HILL', 'RIVER VALLEY FORT EDMONTON',
       'RIVER VALLEY GLENORA', 'RIVER VALLEY GOLD BAR',
       'RIVER VALLEY HERMITAGE', 'RIVER VALLEY HIGHLANDS',
       'RIVER VALLEY KINNAIRD', 'RIVER VALLEY LAURIER',
       'RIVER VALLEY LESSARD NORTH', 'RIVER VALLEY MAYFAIR',
       'RIVER VALLEY OLESKIW', 'RIVER VALLEY RIVERSIDE',
       'RIVER VALLEY RUNDLE', 'RIVER VALLEY TERWILLEGAR',
       'RIVER VALLEY VICTORIA', 'RIVER VALLEY WALTERDALE',
       'RIVER VALLEY WHITEMUD', 'RIVER VALLEY WINDEMERE', "RIVER'S EDGE",
       'RIVERDALE', 'RIVERVIEW AREA', 'ROPER INDUSTRIAL',
       'ROSEDALE INDUSTRIAL', 'ROSENTHAL', 'ROSSDALE', 'ROSSLYN',
       'ROYAL GARDENS', 'RUNDLE HEIGHTS', 'RURAL NORTH EAST HORSE HILL',
       'RURAL NORTH EAST SOUTH STURGEON', 'RUTHERFORD', 'SAKAW', 'SATOO',
       'SCHONSEE', 'SECORD', 'SHEFFIELD INDUSTRIAL', 'SHERBROOKE',
       'SHERWOOD', 'SIFTON PARK', 'SILVER BERRY', 'SKYRATTLER',
       'SOUTH EDMONTON COMMON', 'SOUTH TERWILLEGAR',
       'SOUTHEAST (ANNEXED) INDUSTRIAL', 'SPRUCE AVENUE', 'SPUR LINES',
       'STARLING', 'STEINHAUER', 'STEWART GREENS', 'STILLWATER',
       'STONE INDUSTRIAL', 'STRATHCONA', 'STRATHCONA INDUSTRIAL PARK',
       'STRATHCONA JUNCTION', 'STRATHEARN', 'SUDER GREENS', 'SUMMERLEA',
       'SUMMERSIDE', 'SUNWAPTA INDUSTRIAL', 'SWEET GRASS', 'TAMARACK',
       'TAWA', 'TERRA LOSA', 'TERRACE HEIGHTS', 'TERWILLEGAR TOWNE',
       'THE HAMPTONS', 'THE ORCHARDS AT ELLERSLIE', 'THE UPLANDS',
       'THORNCLIFF', 'TIPASKAN', 'TRUMPETER AREA', 'TWEDDLE PLACE',
       'TWIN BROOKS', 'UNIVERSITY OF ALBERTA',
       'UNIVERSITY OF ALBERTA FARM', 'VIRGINIA PARK', 'WALKER',
       'WEBBER GREENS', 'WEDGEWOOD HEIGHTS', 'WEINLOS', 'WEIR INDUSTRIAL',
       'WELLINGTON', 'WEST JASPER PLACE', 'WEST MEADOWLARK PARK',
       'WEST SHEFFIELD INDUSTRIAL', 'WESTBROOK ESTATE', 'WESTMOUNT',
       'WESTRIDGE', 'WESTVIEW VILLAGE', 'WESTWOOD', 'WHITE INDUSTRIAL',
       'WHITEMUD CREEK RAVINE NORTH', 'WHITEMUD CREEK RAVINE SOUTH',
       'WHITEMUD CREEK RAVINE TWIN BROOKS', 'WÎHKWÊNTÔWIN', 'WILD ROSE',
       'WILSON INDUSTRIAL', 'WINDERMERE', 'WINDERMERE AREA',
       'WINDSOR PARK', 'WINTERBURN INDUSTRIAL AREA EAST',
       'WINTERBURN INDUSTRIAL AREA WEST', 'WOODCROFT',
       'YELLOWHEAD CORRIDOR EAST', 'YELLOWHEAD CORRIDOR WEST', 'YORK',
       'YOUNGSTOWN INDUSTRIAL'], dtype=object)

In [10]:
downtown_properties = property_data[property_data["Neighbourhood"]=="DOWNTOWN"]

In [13]:
print(f"Number of properties in downtown {downtown_properties.shape[0]}")

Number of properties in downtown 10307

In [14]:
downtown_properties.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
106995,1018019,NaN,10040.0,103 STREET NW,1090.0,DOWNTOWN,O-day'min,500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.540052,-113.498326,POINT (-113.49832591329127 53.54005220261335)
106996,1018027,NaN,10405.0,JASPER AVENUE NW,1090.0,DOWNTOWN,O-day'min,0,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.540587,-113.500165,POINT (-113.50016547038064 53.54058675150321)
106997,1018035,NaN,10808.0,99 AVENUE NW,1090.0,DOWNTOWN,O-day'min,16343500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.537776,-113.507119,POINT (-113.50711890782267 53.537776320029145)
106998,1024140,NaN,9839.0,JASPER AVENUE NW,1090.0,DOWNTOWN,O-day'min,150000,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.540915,-113.487252,POINT (-113.48725182521747 53.54091465180801)
106999,1033141,NaN,10820.0,100 AVENUE NW,1090.0,DOWNTOWN,O-day'min,12290500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.539232,-113.507880,POINT (-113.5078803891802 53.539231747129705)

In [15]:
sorted_downtown = downtown_properties.sort_values(by="Assessed Value",ascending=False)
sorted_downtown.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
117266,11012019,NaN,10700.0,104 AVENUE NW,1090.0,DOWNTOWN,O-day'min,342370500,Non Residential,N,COMMERCIAL,COMMERCIAL,NaN,99,1.0,NaN,53.547271,-113.507548,POINT (-113.50754750803071 53.54727130295685)
107029,3010113,NaN,10111.0,104 AVENUE NW,1090.0,DOWNTOWN,O-day'min,303790500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.545713,-113.494631,POINT (-113.49463129239268 53.54571273130205)
116496,10854737,NaN,10220.0,103 AVENUE NW,1090.0,DOWNTOWN,O-day'min,284566500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.545391,-113.497000,POINT (-113.49700047375993 53.545390875408884)
116107,10841805,NaN,9804.0,107 STREET NW,1090.0,DOWNTOWN,O-day'min,269688500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.533957,-113.505303,POINT (-113.50530303364825 53.533957217542564)
115226,10507383,NaN,10175.0,101 STREET NW,1090.0,DOWNTOWN,O-day'min,269044500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.542427,-113.493005,POINT (-113.49300518558233 53.54242689204102)

In [16]:
print(sorted_downtown[:10])

        Account Number Suite  House Number       Street Name  \
117266        11012019   NaN       10700.0     104 AVENUE NW
107029         3010113   NaN       10111.0     104 AVENUE NW
116496        10854737   NaN       10220.0     103 AVENUE NW
116107        10841805   NaN        9804.0     107 STREET NW
115226        10507383   NaN       10175.0     101 STREET NW
117287        11161319   NaN       10423.0     101 STREET NW
107219         3121522   NaN        9700.0  JASPER AVENUE NW
109930         9981060   NaN       10155.0     102 STREET NW
107004         1066331   NaN       10180.0     101 STREET NW
115231        10713425   NaN       10215.0     108 STREET NW

        Neighbourhood ID Neighbourhood       Ward  Assessed Value  \
117266            1090.0      DOWNTOWN  O-day'min       342370500
107029            1090.0      DOWNTOWN  O-day'min       303790500
116496            1090.0      DOWNTOWN  O-day'min       284566500
116107            1090.0      DOWNTOWN  O-day'min       269688500
115226            1090.0      DOWNTOWN  O-day'min       269044500
117287            1090.0      DOWNTOWN  O-day'min       255188500
107219            1090.0      DOWNTOWN  O-day'min       146280500
109930            1090.0      DOWNTOWN  O-day'min       138813500
107004            1090.0      DOWNTOWN  O-day'min       134928000
115231            1090.0      DOWNTOWN  O-day'min       110509500

              Tax Class Garage Assessment Class 1 Assessment Class 2  \
117266  Non Residential      N         COMMERCIAL         COMMERCIAL
107029  Non Residential      N         COMMERCIAL                NaN
116496  Non Residential      N         COMMERCIAL                NaN
116107  Non Residential      N         COMMERCIAL                NaN
115226  Non Residential      N         COMMERCIAL                NaN
117287  Non Residential      N         COMMERCIAL                NaN
107219  Non Residential      N         COMMERCIAL                NaN
109930  Non Residential      N         COMMERCIAL                NaN
107004  Non Residential      N         COMMERCIAL                NaN
115231  Non Residential      N         COMMERCIAL                NaN

       Assessment Class 3  Assessment Class % 1  Assessment Class % 2  \
117266                NaN                    99                   1.0
107029                NaN                   100                   NaN
116496                NaN                   100                   NaN
116107                NaN                   100                   NaN
115226                NaN                   100                   NaN
117287                NaN                   100                   NaN
107219                NaN                   100                   NaN
109930                NaN                   100                   NaN
107004                NaN                   100                   NaN
115231                NaN                   100                   NaN

        Assessment Class % 3   Latitude   Longitude  \
117266                   NaN  53.547271 -113.507548
107029                   NaN  53.545713 -113.494631
116496                   NaN  53.545391 -113.497000
116107                   NaN  53.533957 -113.505303
115226                   NaN  53.542427 -113.493005
117287                   NaN  53.547688 -113.492095
107219                   NaN  53.542819 -113.486685
109930                   NaN  53.541705 -113.494644
107004                   NaN  53.542610 -113.494642
115231                   NaN  53.543810 -113.505666

                                        Point Location
117266   POINT (-113.50754750803071 53.54727130295685)
107029   POINT (-113.49463129239268 53.54571273130205)
116496  POINT (-113.49700047375993 53.545390875408884)
116107  POINT (-113.50530303364825 53.533957217542564)
115226   POINT (-113.49300518558233 53.54242689204102)
117287    POINT (-113.4920945712609 53.54768788752229)
107219   POINT (-113.48668479938223 53.54281857874582)
109930   POINT (-113.49464390513306 53.54170537801964)
107004   POINT (-113.49464155973786 53.54261029845581)
115231  POINT (-113.50566646028214 53.543810376967556)

In [17]:
print(sorted_downtown[["House Number","Street Name","Assessed Value"]][:10])

        House Number       Street Name  Assessed Value
117266       10700.0     104 AVENUE NW       342370500
107029       10111.0     104 AVENUE NW       303790500
116496       10220.0     103 AVENUE NW       284566500
116107        9804.0     107 STREET NW       269688500
115226       10175.0     101 STREET NW       269044500
117287       10423.0     101 STREET NW       255188500
107219        9700.0  JASPER AVENUE NW       146280500
109930       10155.0     102 STREET NW       138813500
107004       10180.0     101 STREET NW       134928000
115231       10215.0     108 STREET NW       110509500

In [19]:
sorted_downtown['Assessed Value in Millions'] = sorted_downtown['Assessed Value']/1000000

In [20]:
print(sorted_downtown[["House Number","Street Name","Assessed Value in Millions"]][:10])

        House Number       Street Name  Assessed Value in Millions
117266       10700.0     104 AVENUE NW                    342.3705
107029       10111.0     104 AVENUE NW                    303.7905
116496       10220.0     103 AVENUE NW                    284.5665
116107        9804.0     107 STREET NW                    269.6885
115226       10175.0     101 STREET NW                    269.0445
117287       10423.0     101 STREET NW                    255.1885
107219        9700.0  JASPER AVENUE NW                    146.2805
109930       10155.0     102 STREET NW                    138.8135
107004       10180.0     101 STREET NW                    134.9280
115231       10215.0     108 STREET NW                    110.5095

In [23]:
# for ellerslie 
ellerslie_properties = property_data[property_data["Neighbourhood"]=="ELLERSLIE"]
ellerslie_properties.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
129818,1068840,NaN,830.0,66 STREET SW,6211.0,ELLERSLIE,Karhiio,780000,Residential,Y,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.425834,-113.443870,POINT (-113.4438702956848 53.425834424756104)
129819,1068857,NaN,730.0,66 STREET SW,6211.0,ELLERSLIE,Karhiio,682500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.426403,-113.443908,POINT (-113.44390846185554 53.42640256801559)
129820,1068865,NaN,6731.0,6 AVENUE SW,6211.0,ELLERSLIE,Karhiio,817000,Residential,Y,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.426991,-113.443909,POINT (-113.44390873847894 53.42699082193762)
129821,1068907,NaN,7130.0,ELLERSLIE ROAD SW,6211.0,ELLERSLIE,Karhiio,985000,Residential,Y,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.425665,-113.448248,POINT (-113.44824811940138 53.42566545167273)
129822,1068915,NaN,430.0,71 STREET SW,6211.0,ELLERSLIE,Karhiio,996500,Residential,Y,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.428673,-113.448083,POINT (-113.44808323588741 53.42867313852655)

In [24]:
print(f"Number of properties in Ellerslie {ellerslie_properties.shape[0]}")

Number of properties in Ellerslie 2425

In [25]:
sorted_ellerslie = ellerslie_properties.sort_values(by="Assessed Value",ascending=False)
sorted_ellerslie.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
132242,11142381,NaN,6830.0,ELLERSLIE ROAD SW,6211.0,ELLERSLIE,Karhiio,20806500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.425683,-113.446221,POINT (-113.44622070957018 53.425682532907196)
130162,9997633,NaN,248.0,EDWARDS DRIVE SW,6211.0,ELLERSLIE,Karhiio,10180500,Other Residential,N,OTHER RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.431075,-113.467960,POINT (-113.46796038555973 53.43107462404453)
132241,11142380,NaN,7030.0,ELLERSLIE ROAD SW,6211.0,ELLERSLIE,Karhiio,4885500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.425537,-113.447096,POINT (-113.44709566812952 53.42553724921464)
129849,3889862,NaN,707.0,75 STREET SW,6211.0,ELLERSLIE,Karhiio,4220500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.425968,-113.449830,POINT (-113.44982993035933 53.42596826997604)
129832,1069046,NaN,6650.0,4 AVENUE SW,6211.0,ELLERSLIE,Karhiio,3692500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.429518,-113.445941,POINT (-113.44594125763857 53.42951847576681)

In [27]:
print(f"{ellerslie_properties[:10]}")

        Account Number Suite  House Number        Street Name  \
129818         1068840   NaN         830.0       66 STREET SW
129819         1068857   NaN         730.0       66 STREET SW
129820         1068865   NaN        6731.0        6 AVENUE SW
129821         1068907   NaN        7130.0  ELLERSLIE ROAD SW
129822         1068915   NaN         430.0       71 STREET SW
129823         1068923   NaN        7120.0        4 AVENUE SW
129824         1068931   NaN         230.0       71 STREET SW
129825         1068956   NaN        6920.0        2 AVENUE SW
129826         1068964   NaN        6720.0        2 AVENUE SW
129827         1068980   NaN         120.0       66 STREET SW

        Neighbourhood ID Neighbourhood     Ward  Assessed Value  \
129818            6211.0     ELLERSLIE  Karhiio          780000
129819            6211.0     ELLERSLIE  Karhiio          682500
129820            6211.0     ELLERSLIE  Karhiio          817000
129821            6211.0     ELLERSLIE  Karhiio          985000
129822            6211.0     ELLERSLIE  Karhiio          996500
129823            6211.0     ELLERSLIE  Karhiio          939000
129824            6211.0     ELLERSLIE  Karhiio          851500
129825            6211.0     ELLERSLIE  Karhiio          896000
129826            6211.0     ELLERSLIE  Karhiio          967000
129827            6211.0     ELLERSLIE  Karhiio         3038500

              Tax Class Garage Assessment Class 1 Assessment Class 2  \
129818      Residential      Y        RESIDENTIAL                NaN
129819      Residential      N        RESIDENTIAL                NaN
129820      Residential      Y        RESIDENTIAL                NaN
129821      Residential      Y        RESIDENTIAL                NaN
129822      Residential      Y        RESIDENTIAL                NaN
129823      Residential      Y        RESIDENTIAL                NaN
129824      Residential      Y        RESIDENTIAL                NaN
129825      Residential      Y        RESIDENTIAL                NaN
129826      Residential      Y        RESIDENTIAL                NaN
129827  Non Residential      N         COMMERCIAL        RESIDENTIAL

       Assessment Class 3  Assessment Class % 1  Assessment Class % 2  \
129818                NaN                   100                   NaN
129819                NaN                   100                   NaN
129820                NaN                   100                   NaN
129821                NaN                   100                   NaN
129822                NaN                   100                   NaN
129823                NaN                   100                   NaN
129824                NaN                   100                   NaN
129825                NaN                   100                   NaN
129826                NaN                   100                   NaN
129827                NaN                    80                  20.0

        Assessment Class % 3   Latitude   Longitude  \
129818                   NaN  53.425834 -113.443870
129819                   NaN  53.426403 -113.443908
129820                   NaN  53.426991 -113.443909
129821                   NaN  53.425665 -113.448248
129822                   NaN  53.428673 -113.448083
129823                   NaN  53.429744 -113.448084
129824                   NaN  53.431009 -113.448063
129825                   NaN  53.431591 -113.446360
129826                   NaN  53.431259 -113.444174
129827                   NaN  53.431919 -113.444174

                                        Point Location
129818   POINT (-113.4438702956848 53.425834424756104)
129819   POINT (-113.44390846185554 53.42640256801559)
129820   POINT (-113.44390873847894 53.42699082193762)
129821   POINT (-113.44824811940138 53.42566545167273)
129822   POINT (-113.44808323588741 53.42867313852655)
129823   POINT (-113.44808398808561 53.42974396019809)
129824   POINT (-113.44806332478667 53.43100918837237)
129825    POINT (-113.4463600451879 53.43159144537515)
129826   POINT (-113.44417379601364 53.43125916003811)
129827  POINT (-113.44417421931571 53.431918672104686)

In [28]:
print(sorted_ellerslie[["House Number","Street Name","Assessed Value"]][:10])

        House Number        Street Name  Assessed Value
132242        6830.0  ELLERSLIE ROAD SW        20806500
130162         248.0   EDWARDS DRIVE SW        10180500
132241        7030.0  ELLERSLIE ROAD SW         4885500
129849         707.0       75 STREET SW         4220500
129832        6650.0        4 AVENUE SW         3692500
129848         811.0       75 STREET SW         3255000
129827         120.0       66 STREET SW         3038500
129850         635.0       75 STREET SW         2696500
131713         371.0       91 STREET SW         2615500
129847        6704.0  ELLERSLIE ROAD SW         2308500

In [29]:
sorted_ellerslie['Assessed Value in Millions'] = sorted_ellerslie["Assessed Value"]/1000000

In [30]:
print(sorted_ellerslie[["House Number","Street Name","Assessed Value in Millions"]][:10])

        House Number        Street Name  Assessed Value in Millions
132242        6830.0  ELLERSLIE ROAD SW                     20.8065
130162         248.0   EDWARDS DRIVE SW                     10.1805
132241        7030.0  ELLERSLIE ROAD SW                      4.8855
129849         707.0       75 STREET SW                      4.2205
129832        6650.0        4 AVENUE SW                      3.6925
129848         811.0       75 STREET SW                      3.2550
129827         120.0       66 STREET SW                      3.0385
129850         635.0       75 STREET SW                      2.6965
131713         371.0       91 STREET SW                      2.6155
129847        6704.0  ELLERSLIE ROAD SW                      2.3085